import './globals.css'
import Navbar from '@components/Navbar'
import WhatsappIcon from '@components/WhatsappIcon'
import formatPhoneNumber from '@utils/formatPhoneNumber'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar />
        {children}
        <a
          className="btn fixed bottom-5 right-5"
          target="_blank"
          href={`https://api.whatsapp.com/send?phone=${formatPhoneNumber(
            '+55 48 99921-1237',
          )}`}
          rel="noreferrer"
        >
          <WhatsappIcon />
        </a>
      </body>
    </html>
  )
}
