import { DiJqueryLogo } from 'react-icons/di'
import Link from 'next/link'
import React from 'react'
import Head from 'next/head'

export default function Header() {
  return (
    <React.Fragment>
      <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <header className="flex fixed top-0 left-0 py-5 w-full justify-around">
        <div>
          <DiJqueryLogo/>
        </div>
        <nav>
          <ul className="flex">
            {['home', 'sobre', 'especialidades', 'curso', 'materiais', 'blog'].map((i, k) => (
              <li className="mx-1" key={k}>
                <Link href={`/${i === 'home' ? '' : i}`}>{i}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </header>
    </React.Fragment>
  )
}